### ISSUE TITLE
Add possibillity to limit component for specfic elements

### ISSUE THREAD

**Issue by kev1896** [iizunats/iizuna#20]
**Is your feature request related to a problem? Please describe.**
it is possible to include functionality to specific elements that would break if placed on child elements.

**Describe the solution you'd like**
Add limit selector to component decorator. If an element does not match the selector, show a warning in the console.

**Comment by Nano1237** [comment]
Feature was finally added in commit 258bdb13bd8b9c8d44e037672b18471a7aaf4fa6
